name: Markdown file validation

on:
  push:

jobs:
  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@89-fix-option-to-markdown-check-does-nothing-and-may-be-hiding-actual-errors
