name: Dev-Rel-Docs integration workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    secrets: inherit

  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
